language: java
jdk:
- openjdk8
before_install:
- openssl aes-256-cbc -K $encrypted_65184c842012_key -iv $encrypted_65184c842012_iv -in client-secret.json.enc -out client-secret.json -d
- chmod +x gradlew
addons:
  sonarcloud:
    organization: jonniewanathan-github
    token:
      secure: ad83a13726e8e5d00debca0d872d9d2489169548
script:
- gradle check
- gradle build
- git fetch --unshallow
- gradle sonarqube
- mv app.yaml ./build/libs/app.yaml
- mv client-secret.json ./build/libs/client-secret.json
- cd ./build/libs/

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
    
notifications:
  slack: devopstesting-hq:uDHXvSJ70af7ySjupMqIPTMH
  email:
    recipients:
    - jonathan41@hotmail.com
    on_success: always
    on_failure: always

deploy:
  provider: gae
  keyfile: client-secret.json
  project: rock-sublime-238612
  skip_cleanup: true
