language: java
jdk:
- openjdk8
before_install:
- openssl aes-256-cbc -K $encrypted_65184c842012_key -iv $encrypted_65184c842012_iv -in client-secret.json.enc -out client-secret.json -d
- chmod +x gradlew
addons:
  sonarcloud:
    organization: jonniewanathan-github
    token:
      secure: ad83a13726e8e5d00debca0d872d9d2489169548
script:
- gradle check
- gradle build
- gradle sonarqube

deploy:
  provider: gae
  keyfile: client-secret.json
  project: rock-sublime-238612
  skip_cleanup: true
