language: java
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
addons:
  sonarcloud:
    organization: jonniewanathan-github
    token:
      secure: ad83a13726e8e5d00debca0d872d9d2489169548
script:
- gradle check
- gradle build
- gradle sonarqube
deploy:
  provider: gae
  keyfile: client-secret.json
  file: /build/lib/gs-testing-web-0.1.0.jar
  project: rock-sublime-238612
