runtime: java
env: flex
runtime_config:
  jdk: openjdk8

handlers:
- url: /.*
  script: this field is required, but ignored
# [END gae_flex_quickstart_yaml]

resources:
  cpu: 2
  memory_gb: 2.3
  disk_size_gb: 5
  volumes:
  - name: ramdisk1
    volume_type: tmpfs
    size_gb: 0.5
